using System;

namespace SDL_Sharp;
public static unsafe partial class SDL
{
    internal const int SDLK_MASK = 1 << 30;
}

public enum Keycode
{
    Unknown = 0,

    Return = '\r',
    Escape = 27,
    Backspace = '\b',
    Tab = '\t',
    Space = ' ',
    Exclaim = '!',
    Quotedbl = '"',
    Hash = '#',
    Percent = '%',
    Dollar = '$',
    Ampersand = '&',
    Quote = '\'',
    LeftParen = '(',
    RightParen = ')',
    Asterisk = '*',
    Plus = '+',
    Comma = ',',
    Minus = '-',
    Period = '.',
    Slash = '/',
    D0 = '0',
    D1 = '1',
    D2 = '2',
    D3 = '3',
    D4 = '4',
    D5 = '5',
    D6 = '6',
    D7 = '7',
    D8 = '8',
    D9 = '9',
    Colon = ':',
    SemiColon = ';',
    Less = '<',
    Equals = '=',
    Greater = '>',
    Question = '?',
    At = '@',
    /*
       Skip uppercase letters
     */
    LeftBracket = '[',
    Backslash = '\\',
    RightBracket = ']',
    Caret = '^',
    Underscore = '_',
    BackQuote = '`',
    A = 'a',
    B = 'b',
    C = 'c',
    D = 'd',
    E = 'e',
    F = 'f',
    G = 'g',
    H = 'h',
    I = 'i',
    J = 'j',
    K = 'k',
    L = 'l',
    M = 'm',
    N = 'n',
    O = 'o',
    P = 'p',
    Q = 'q',
    R = 'r',
    S = 's',
    T = 't',
    U = 'u',
    V = 'v',
    W = 'w',
    X = 'x',
    Y = 'y',
    Z = 'z',

    CapsLock = Scancode.CapsLock | SDL.SDLK_MASK,

    F1 = Scancode.F1 | SDL.SDLK_MASK,
    F2 = Scancode.F2 | SDL.SDLK_MASK,
    F3 = Scancode.F3 | SDL.SDLK_MASK,
    F4 = Scancode.F4 | SDL.SDLK_MASK,
    F5 = Scancode.F5 | SDL.SDLK_MASK,
    F6 = Scancode.F6 | SDL.SDLK_MASK,
    F7 = Scancode.F7 | SDL.SDLK_MASK,
    F8 = Scancode.F8 | SDL.SDLK_MASK,
    F9 = Scancode.F9 | SDL.SDLK_MASK,
    F10 = Scancode.F10 | SDL.SDLK_MASK,
    F11 = Scancode.F11 | SDL.SDLK_MASK,
    F12 = Scancode.F12 | SDL.SDLK_MASK,

    PrintScreen = Scancode.PrintScreen | SDL.SDLK_MASK,
    ScrollLock = Scancode.ScrollLock | SDL.SDLK_MASK,
    Pause = Scancode.Pause | SDL.SDLK_MASK,
    Insert = Scancode.Insert | SDL.SDLK_MASK,
    Home = Scancode.Home | SDL.SDLK_MASK,
    PageUp = Scancode.PageUp | SDL.SDLK_MASK,
    Delete = 127,
    End = Scancode.End | SDL.SDLK_MASK,
    PageDown = Scancode.PageDown | SDL.SDLK_MASK,
    Right = Scancode.Right | SDL.SDLK_MASK,
    Left = Scancode.Left | SDL.SDLK_MASK,
    Down = Scancode.Down | SDL.SDLK_MASK,
    Up = Scancode.Up | SDL.SDLK_MASK,

    NumLockClear = Scancode.NumLockClear | SDL.SDLK_MASK,
    KeyPadDivide = Scancode.KeyPadDivide | SDL.SDLK_MASK,
    KeyPadMultiply = Scancode.KeyPadMultiply | SDL.SDLK_MASK,
    KeyPadMinus = Scancode.KeyPadMinus | SDL.SDLK_MASK,
    KeyPadPlus = Scancode.KeyPadPlus | SDL.SDLK_MASK,
    KeyPadEnter = Scancode.KeyPadEnter | SDL.SDLK_MASK,
    KeyPad1 = Scancode.KeyPad1 | SDL.SDLK_MASK,
    KeyPad2 = Scancode.KeyPad2 | SDL.SDLK_MASK,
    KeyPad3 = Scancode.KeyPad3 | SDL.SDLK_MASK,
    KeyPad4 = Scancode.KeyPad4 | SDL.SDLK_MASK,
    KeyPad5 = Scancode.KeyPad5 | SDL.SDLK_MASK,
    KeyPad6 = Scancode.KeyPad6 | SDL.SDLK_MASK,
    KeyPad7 = Scancode.KeyPad7 | SDL.SDLK_MASK,
    KeyPad8 = Scancode.KeyPad8 | SDL.SDLK_MASK,
    KeyPad9 = Scancode.KeyPad9 | SDL.SDLK_MASK,
    KeyPad0 = Scancode.KeyPad0 | SDL.SDLK_MASK,
    KeyPadPeriod = Scancode.KeyPadPeriod | SDL.SDLK_MASK,

    Application = Scancode.Application | SDL.SDLK_MASK,
    Power = Scancode.Power | SDL.SDLK_MASK,
    KeyPadEquals = Scancode.KeyPadEquals | SDL.SDLK_MASK,
    F13 = Scancode.F13 | SDL.SDLK_MASK,
    F14 = Scancode.F14 | SDL.SDLK_MASK,
    F15 = Scancode.F15 | SDL.SDLK_MASK,
    F16 = Scancode.F16 | SDL.SDLK_MASK,
    F17 = Scancode.F17 | SDL.SDLK_MASK,
    F18 = Scancode.F18 | SDL.SDLK_MASK,
    F19 = Scancode.F19 | SDL.SDLK_MASK,
    F20 = Scancode.F20 | SDL.SDLK_MASK,
    F21 = Scancode.F21 | SDL.SDLK_MASK,
    F22 = Scancode.F22 | SDL.SDLK_MASK,
    F23 = Scancode.F23 | SDL.SDLK_MASK,
    F24 = Scancode.F24 | SDL.SDLK_MASK,
    Execute = Scancode.Execute | SDL.SDLK_MASK,
    Help = Scancode.Help | SDL.SDLK_MASK,
    Menu = Scancode.Menu | SDL.SDLK_MASK,
    Select = Scancode.Select | SDL.SDLK_MASK,
    Stop = Scancode.Stop | SDL.SDLK_MASK,
    Again = Scancode.Again | SDL.SDLK_MASK,
    Undo = Scancode.Undo | SDL.SDLK_MASK,
    Cut = Scancode.Cut | SDL.SDLK_MASK,
    Copy = Scancode.Copy | SDL.SDLK_MASK,
    Paste = Scancode.Paste | SDL.SDLK_MASK,
    Find = Scancode.Find | SDL.SDLK_MASK,
    Mute = Scancode.Mute | SDL.SDLK_MASK,
    VolumeUp = Scancode.VolumeUp | SDL.SDLK_MASK,
    VolumeDown = Scancode.VolumeDown | SDL.SDLK_MASK,
    KeyPadComma = Scancode.KeyPadComma | SDL.SDLK_MASK,
    KeyPadEqualsAS400 = Scancode.KeyPadEqualsAS400 | SDL.SDLK_MASK,

    AltErase = Scancode.AltErase | SDL.SDLK_MASK,
    SysReq = Scancode.SysReq | SDL.SDLK_MASK,
    Cancel = Scancode.Cancel | SDL.SDLK_MASK,
    Clear = Scancode.Clear | SDL.SDLK_MASK,
    Prior = Scancode.Prior | SDL.SDLK_MASK,
    Return2 = Scancode.Return2 | SDL.SDLK_MASK,
    Separator = Scancode.Separator | SDL.SDLK_MASK,
    Out = Scancode.Out | SDL.SDLK_MASK,
    Oper = Scancode.Oper | SDL.SDLK_MASK,
    ClearAgain = Scancode.ClearAgain | SDL.SDLK_MASK,
    CrSel = Scancode.CrSel | SDL.SDLK_MASK,
    ExSel = Scancode.ExSel | SDL.SDLK_MASK,

    KeyPad00 = Scancode.KeyPad00 | SDL.SDLK_MASK,
    KeyPad000 = Scancode.KeyPad000 | SDL.SDLK_MASK,
    ThousandsSeparator = Scancode.ThousandsSeparator | SDL.SDLK_MASK,
    DecimalSeparator = Scancode.DecimalSeparator | SDL.SDLK_MASK,
    CurrencyUnit = Scancode.CurrencyUnit | SDL.SDLK_MASK,
    CurrencySubunit = Scancode.CurrencySubunit | SDL.SDLK_MASK,
    KeyPadLeftParen = Scancode.KeyPadLeftParen | SDL.SDLK_MASK,
    KeyPadRightParen = Scancode.KeyPadRightParen | SDL.SDLK_MASK,
    KeyPadLeftBrace = Scancode.KeyPadLeftBrace | SDL.SDLK_MASK,
    KeyPadRightBrace = Scancode.KeyPadRightBrace | SDL.SDLK_MASK,
    KeyPadTab = Scancode.KeyPadTab | SDL.SDLK_MASK,
    KeyPadBackspace = Scancode.KeyPadBackspace | SDL.SDLK_MASK,
    KeyPadA = Scancode.KeyPadA | SDL.SDLK_MASK,
    KeyPadB = Scancode.KeyPadB | SDL.SDLK_MASK,
    KeyPadC = Scancode.KeyPadC | SDL.SDLK_MASK,
    KeyPadD = Scancode.KeyPadD | SDL.SDLK_MASK,
    KeyPadE = Scancode.KeyPadE | SDL.SDLK_MASK,
    KeyPadF = Scancode.KeyPadF | SDL.SDLK_MASK,
    KeyPadXor = Scancode.KeyPadXor | SDL.SDLK_MASK,
    KeyPadPower = Scancode.KeyPadPower | SDL.SDLK_MASK,
    KeyPadPercent = Scancode.KeyPadPercent | SDL.SDLK_MASK,
    KeyPadLess = Scancode.KeyPadLess | SDL.SDLK_MASK,
    KeyPadGreater = Scancode.KeyPadGreater | SDL.SDLK_MASK,
    KeyPadAmpersand = Scancode.KeyPadAmpersand | SDL.SDLK_MASK,
    KeyPadDoubleAmpersand = Scancode.KeyPadDoubleAmpersand | SDL.SDLK_MASK,
    KeyPadVerticalBar = Scancode.KeyPadVerticalBar | SDL.SDLK_MASK,
    KeyPadDoubleVerticalBar = Scancode.KeyPadDoubleVerticalBar | SDL.SDLK_MASK,
    KeyPadColon = Scancode.KeyPadColon | SDL.SDLK_MASK,
    KeyPadHash = Scancode.KeyPadHash | SDL.SDLK_MASK,
    KeyPadSpace = Scancode.KeyPadSpace | SDL.SDLK_MASK,
    KeyPadAt = Scancode.KeyPadAt | SDL.SDLK_MASK,
    KeyPadExclam = Scancode.KeyPadExclam | SDL.SDLK_MASK,
    KeyPadMemStore = Scancode.KeyPadMemStore | SDL.SDLK_MASK,
    KeyPadMemRecall = Scancode.KeyPadMemRecall | SDL.SDLK_MASK,
    KeyPadMemClear = Scancode.KeyPadMemClear | SDL.SDLK_MASK,
    KeyPadMemAdd = Scancode.KeyPadMemAdd | SDL.SDLK_MASK,
    KeyPadMemSubtract = Scancode.KeyPadMemSubtract | SDL.SDLK_MASK,
    KeyPadMemMultiply = Scancode.KeyPadMemMultiply | SDL.SDLK_MASK,
    KeyPadMemDivide = Scancode.KeyPadMemDivide | SDL.SDLK_MASK,
    KeyPadPlusMinus = Scancode.KeyPadPlusMinus | SDL.SDLK_MASK,
    KeyPadClear = Scancode.KeyPadClear | SDL.SDLK_MASK,
    KeyPadClearEntry = Scancode.KeyPadClearEntry | SDL.SDLK_MASK,
    KeyPadBinary = Scancode.KeyPadBinary | SDL.SDLK_MASK,
    KeyPadOctal = Scancode.KeyPadOctal | SDL.SDLK_MASK,
    KeyPadDecimal = Scancode.KeyPadDecimal | SDL.SDLK_MASK,
    KeyPadHexadecimal = Scancode.KeyPadHexadecimal | SDL.SDLK_MASK,

    LCtrl = Scancode.LCtrl | SDL.SDLK_MASK,
    LShift = Scancode.LShift | SDL.SDLK_MASK,
    LAlt = Scancode.LAlt | SDL.SDLK_MASK,
    LGui = Scancode.LGui | SDL.SDLK_MASK,
    RCtrl = Scancode.RCtrl | SDL.SDLK_MASK,
    RShift = Scancode.RShift | SDL.SDLK_MASK,
    RAlt = Scancode.RAlt | SDL.SDLK_MASK,
    RGui = Scancode.RGui | SDL.SDLK_MASK,

    Mode = Scancode.Mode | SDL.SDLK_MASK,

    AudioNext = Scancode.AudioNext | SDL.SDLK_MASK,
    AudioPrev = Scancode.AudioPrev | SDL.SDLK_MASK,
    AudioStop = Scancode.AudioStop | SDL.SDLK_MASK,
    AudioPlay = Scancode.AudioPlay | SDL.SDLK_MASK,
    AudioMute = Scancode.AudioMute | SDL.SDLK_MASK,
    MediaSelect = Scancode.MediaSelect | SDL.SDLK_MASK,
    Www = Scancode.Www | SDL.SDLK_MASK,
    Mail = Scancode.Mail | SDL.SDLK_MASK,
    Calculator = Scancode.Calculator | SDL.SDLK_MASK,
    Computer = Scancode.Computer | SDL.SDLK_MASK,
    AcSearch = Scancode.AcSearch | SDL.SDLK_MASK,
    AcHome = Scancode.AcHome | SDL.SDLK_MASK,
    AcBack = Scancode.AcBack | SDL.SDLK_MASK,
    AcForward = Scancode.AcForward | SDL.SDLK_MASK,
    AcStop = Scancode.AcStop | SDL.SDLK_MASK,
    AcRefresh = Scancode.AcRefresh | SDL.SDLK_MASK,
    AcBookmarks = Scancode.AcBookmarks | SDL.SDLK_MASK,

    BrightnessDown = Scancode.BrightnessDown | SDL.SDLK_MASK,
    BrightnessUp = Scancode.BrightnessUp | SDL.SDLK_MASK,
    DisplaySwitch = Scancode.DisplaySwitch | SDL.SDLK_MASK,
    KbdIllumToggle = Scancode.KbdIllumToggle | SDL.SDLK_MASK,
    KbdIllumDown = Scancode.KbdIllumDown | SDL.SDLK_MASK,
    KbdIllumUp = Scancode.KbdIllumUp | SDL.SDLK_MASK,
    Eject = Scancode.Eject | SDL.SDLK_MASK,
    Sleep = Scancode.Sleep | SDL.SDLK_MASK,
    App1 = Scancode.App1 | SDL.SDLK_MASK,
    App2 = Scancode.App2 | SDL.SDLK_MASK,

    AudioRewind = Scancode.AudioRewind | SDL.SDLK_MASK,
    AudioFastForward = Scancode.AudioFastForward | SDL.SDLK_MASK
}

[Flags]
public enum KeyModifier : ushort
{
    None = 0x0000,
    LeftShift = 0x0001,
    RightShift = 0x0002,
    LeftCtrl = 0x0040,
    RightCtrl = 0x0080,
    LeftAlt = 0x0100,
    RightAlt = 0x0200,
    LeftGui = 0x0400,
    RightGui = 0x0800,
    Num = 0x1000,
    Caps = 0x2000,
    Mode = 0x4000,
    Reserved = 0x8000,

    Ctrl = LeftCtrl | RightCtrl,
    Shift = LeftShift | RightShift,
    Alt = LeftAlt | RightAlt,
    Gui = LeftGui | RightGui
}
